# Generated by Django 4.2.5 on 2023-09-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('ingredient', models.TextField(blank=True, default='', max_length=255)),
                ('procedures', models.TextField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
