# Generated by Django 4.2.5 on 2023-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_app',
            name='ingredient',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe_app',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe_app',
            name='procedures',
            field=models.TextField(default='', max_length=255),
        ),
    ]
