# Generated by Django 4.2.5 on 2023-09-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0004_remove_recipe_app_ingredients_recipe_app_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe_app',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe_app',
            name='ingredients',
            field=models.ManyToManyField(to='Recipe_app.ingredient'),
        ),
    ]
